language: node_js
sudo: required
matrix:
  include:
    - node_js: "stable"
      before_script:
        - apt install python
        - npm install -g mocha istanbul coveralls mocha-lcov-reporter --save-dev
      after_success:
        - npm run coveralls
    
